name: flutter_wootric
description: A Wootric SDK Wrapper for Flutter to support in app NPS collection. You need as minimumn a free Wootric Account with valid ClientId and AccountToken.
version: 0.1.3
homepage: https://www.claimsforce.com
repository: https://github.com/claimsforce-gmbh/flutter-wootric
issue_tracker: https://github.com/claimsforce-gmbh/flutter-wootric/issues
documentation: https://github.com/claimsforce-gmbh/flutter-wootric#readme

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.2.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.claimsforce.wootric.flutter_wootric
        pluginClass: FlutterWootricPlugin
      ios:
        pluginClass: FlutterWootricPlugin
